// SPDX-FileCopyrightText: Copyright (c) Kitware Inc.
// SPDX-License-Identifier: BSD-3-Clause
// .NAME vtkMyElevationFilter - generate scalars along a specified direction
// .SECTION Description
// vtkMyElevationFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#pragma once

#include <CinemaAlgorithm.h>
#include "CinemaWriterModule.h" // for export macro

class CINEMAWRITER_EXPORT CinemaWriter : public CinemaAlgorithm {

public:
  static CinemaWriter* New();
  vtkTypeMacro(CinemaWriter, CinemaAlgorithm);

  vtkSetMacro(OutputDirectory, const std::string &);
  vtkGetMacro(OutputDirectory, std::string);

  vtkSetMacro(CompressionLevel, const int);
  vtkGetMacro(CompressionLevel, int);

  int CreateDataCSV() const;
  int DeleteDatabase() const;

protected:
  CinemaWriter();
  ~CinemaWriter();

  int RequestData(vtkInformation *request,
                 vtkInformationVector **inputVector,
                 vtkInformationVector *outputVector) override;
  int FillInputPortInformation(int port, vtkInformation *info) override;
  int FillOutputPortInformation(int port, vtkInformation *info) override;

private:
  CinemaWriter(const CinemaWriter&) = delete;
  void operator=(const CinemaWriter&) = delete;

  std::string OutputDirectory{""};
  int CompressionLevel{5};
};
